package model

// CanvasElement represents a shape or note element on the whiteboard.
type CanvasElement struct {
	ID       string  `json:"id"`
	Type     string  `json:"type"` // "geo" or "note"
	Geo      string  `json:"geo,omitempty"`
	Color    string  `json:"color"`
	Position string  `json:"position"`
	X        float64 `json:"x,omitempty"`
	Y        float64 `json:"y,omitempty"`
	W        float64 `json:"w,omitempty"`
	H        float64 `json:"h,omitempty"`
	Text     string  `json:"text,omitempty"`
}

// ClientMessage is the message payload sent by the frontend via WebSocket.
type ClientMessage struct {
	Text        string          `json:"text"`
	CanvasState []CanvasElement `json:"canvas_state"`
}

// DrawAction represents a single mutation instruction sent back to the frontend.
type DrawAction struct {
	Command  string                 `json:"command"`            // "create_shape", "modify_shape", "delete_shape", "clear_canvas"
	Type     string                 `json:"type,omitempty"`     // "geo", "note"
	TargetID string                 `json:"target_id,omitempty"`
	Props    map[string]interface{} `json:"props,omitempty"`    // e.g. color, geo, w, h, text
	Position string                 `json:"position,omitempty"` // "center", "top_left", etc.
	X        *float64               `json:"x,omitempty"`
	Y        *float64               `json:"y,omitempty"`
	Text     string                 `json:"text,omitempty"`
}

// ServerResponse is the JSON response wrapper containing parsed actions and feedback.
type ServerResponse struct {
	TaskAnalysis   string       `json:"task_analysis,omitempty"`
	StepByStepPlan []string     `json:"step_by_step_plan,omitempty"`
	Actions        []DrawAction `json:"actions"`
	RawText        string       `json:"raw_text,omitempty"` // Echoed user voice input for verification
	Feedback       string       `json:"feedback,omitempty"` // Feedback message for user
	VoiceReply     string       `json:"voice_reply,omitempty"` // TTS reply generated by LLM
}
